### PR TITLE
feat(drivers): adds support for a sqlite driver

### LINKED ISSUE #188: SQLite driver
### Describe the feature

I was wondering if there is a plan to have a SQLite driver, similar to what PlanetScale driver looks like. Otherwise, I could attempt to write one if you are interested.

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by threkk**
First version of a possible SQLite driver, very much open for any feedback. It is heavily based on the current planetscale driver. It still needs:

- [x] Support for raw mode.
- [x] Support for meta keys.
- [x] Code clean up.
- [ ] Documentation.

Closes #188

### CODE REVIEW

**Comment by threkk** [comment]
Hello! Sorry for the long time without updating this draft. I added support for the meta operations, and decided to not implement the experimental features until they are stable. I reviewed the documentation and corrected some small bugs I found. 

The only remaining task is to write the documentation, but I would say this is ready for a code review. Let me know if you have any doubt about the implementation decisions. I will write the documentation ASAP.

**Comment by pi0** [comment]
Hi dear @threkk. Sorry for delay on review. Actually i have not merged your PR because we are working on a standard SQL layer for unjs and i think with that, we can rebase sqlite driver. I will keep you posted.

**Comment by threkk** [comment]
What do you have in mind? :) If you give me some insights, I can start looking into it, so it is ready by the time you are done.

**Comment by pi0** [comment]
Invited you to private repo

**Comment by pi0** [comment]
Hi, thanks again for your work on this ❤️ 

Let's track via https://github.com/unjs/unstorage/issues/400 (PR welcome!)

**Pull request closed without merging**
