### PR TITLE
feat: support cloudflare options with setItem

### PR DESCRIPTION
**Pull request by Hebilicious**
### 🔗 Linked issue

Resolves https://github.com/unjs/unstorage/issues/32

First part of https://github.com/unjs/unstorage/pull/236

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR allows the ability to pass options to the setItem method while using the cloudflare driver : 

```ts
await storage.setItem("key", "value", 
{ 
  expiration: 1578435000, 
  expiration_ttl: 300, // http driver
  expirationTtl: 300, // binding driver
  base64: false,
  metadata: { someMetadataKey: "someMetadataValue" }
});
```

- implements the cloudflare options such as metadata, expiring keys, etc. 
	- Forward the 3rd argument (options) to the `cloudflare-kv-binding`and `cloudflare-kv-http` drivers `setItem` method.
	- Changes the put implementation of the `cloudflare-kv-http` to use the bulk API ([to support all options](https://developers.cloudflare.com/api/operations/workers-kv-namespace-write-multiple-key-value-pairs)). 

## Options "API design"

For now I'm leverage the 3rd argument of the setItem method, but I was thinking that we could require users to pass them nested under a key (`{ cloudflare: {} }`), or use a 4th argument, in-case we want to keep the 3rd argument open for unstorage specific options... Thoughts ?

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Hebilicious** [comment]
Refactor with namespace

**Comment by Hebilicious** [comment]
Added a generic ttl parameters, as well as a default ttl configurable in the options. 
Also added namespaced options under the kebabcased driver name :  `cloudflareKvBinding` and `cloudflareKvHttp`. 
Since they are different we can't use the same key.

**Comment by pi0** [comment]
> Refactor TransactionOptions into 2 new types that are more explicit, SetItemOptions and GetItemOptions, and have the generic ttl?: number, and fix the type bugs without changing behaviours.

As i mentioned in other PR, it would make sense to support one kind of options interface (even if some option keys are not used by read operation). Particulary for `ttl` that should be also supported for passive key expiration for drivers not supporting ttl.

> Refactor R2 with a nested key (id say make the breaking change as its only 4d old, would give full type safety, and we discussed this already)

👍🏼

**Comment by pi0** [comment]
If it is only for type, surely we can add `ttl?` type to generic `TransactionOptions` in this PR 👍🏼

**Comment by Hebilicious** [comment]
@pi0 I would be happy to revisit splitting TransactionOptions once it's actually needed. For now I've implemented everything in this PR according to your requirements.
http and r2 needs to be slightly tweaked because we are no longer using any for TransactionOptions. This doesn't affect the runtime.

**Comment by pi0** [comment]
Thanks for the updates. As an update, i still need to double check all changes there are too many changes some are unrelated to the feature we want to add.

**Comment by Hebilicious** [comment]
> Thanks for the updates. As an update, i still need to double check all changes there are too many changes some are unrelated to the feature we want to add.

@pi0 I had to change these things because according to the docs the put api doesn't support ttl, only the [bulk](https://developers.cloudflare.com/api/operations/workers-kv-namespace-write-multiple-key-value-pairs) API does, and updating the types has a slightly larger blast radius.

**Comment by pi0** [comment]
PR is stalled and with too many changes, have to rework this. 

(but again really appreciate your previous help on this ❤️ )

**Pull request closed without merging**
