### PR TITLE
feat(drivers): add session storage driver

### PR DESCRIPTION
**Pull request by CorentinTh**
Hi !

This PR adds the [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) driver

- [x] Driver implementation
- [x] Unit test
- [x] Updated doc

### CODE REVIEW

**Comment by CorentinTh** [comment]
It has a similar api to the local storage driver, so one could have use :
```js
const storage = createStorage({
  driver: localStorageDriver({ base: "app:", localStorage: window.sessionStorage }),
});
```
So what do you think of this driver ?

**Comment by CorentinTh** [comment]
It could also be written like :

**Comment by CorentinTh** [comment]
Since they have a similar API with localstorage, it can also be written like :

```js
import { defineDriver } from "./utils";
import localStorageDriver from './localstorage'

export interface SessionStorageOptions {
  base?: string;
  window?: typeof window;
  sessionStorage?: typeof window.sessionStorage;
}

export default defineDriver((opts: SessionStorageOptions = {}) => {
  if (!opts.window) {
    opts.window = typeof window !== "undefined" ? window : undefined;
  }
  if (!opts.sessionStorage) {
    opts.sessionStorage = opts.window?.sessionStorage;
  }
  if (!opts.sessionStorage) {
    throw new Error("localStorage not available");
  }

 return localStorageDriver({...opts, localStorage: opts.sessionStorage})
});
```
But it induces coupling between drivers, and decrease maintainability 🤷🏻

**Comment by CorentinTh** [comment]
Hi @pi0 !
Let me know if I have something to change 🙏🏻

**Review by pi0 — APPROVED** [review]
LGTM 💯 

Regarding refactor to extend local storage, let's see how frequently we need to update both and if makes sense to extend for easier maintenance.

**Pull request merged**
