### PR TITLE
refactor(getItems): support string input for value lookups

### PR DESCRIPTION
**Pull request by GalacticHypernova**
### 🔗 Linked issue

#383 
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This refactors getItems to support string input for file lookups, as per the feedback provided.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GalacticHypernova** [comment]
@pi0 just to make sure before I begin the work, is this what you meant by a refactor?

**Comment by pi0** [comment]
Oh sorry if i didn't explain well. What I meant was to export a new function from [utils.ts](https://github.com/unjs/unstorage/blob/main/src/utils.ts) with `findItems(storage: Storage, matcher: string, opts: { raw?: boolean } = {}` signature. This utility is not adding to the core bundle size but can be used to easily do search operation.

**Comment by GalacticHypernova** [comment]
Ah, I see, my bad for misunderstanding. I will do so

**Comment by pi0** [comment]
please feel free to reopen one had a chance or if still interested in adding `findItems` util 👍🏼

**Pull request closed without merging**
