### PR TITLE
Added a setKeyExpire method for the redis driver to set the expiration time of the key.

### PR DESCRIPTION
**Pull request by rd-carter**
redis.setItem('hi', 'carter');
redis.setKeyExpire('hi', 1); // 1s
#87

### CODE REVIEW

**Comment by rd-carter** [comment]
@pi0

**Comment by itpropro** [comment]
Hi @rd-carter,
thanks for your contribution! Can you please update the docs and the test suits to include the new property?

**Comment by rd-carter** [comment]
> 你好@rd-carter， 感谢您的贡献！您能否更新文档和测试服以包含新属性？

okay

**Comment by rd-carter** [comment]
@itpropro this is the new pr.
[https://github.com/unjs/unstorage/pull/150](url)

**Pull request closed without merging**
