### PR TITLE
perf(fs): refactor readDirRecursive to await at the end with `flat`

### PR DESCRIPTION
**Pull request by GalacticHypernova**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

By deferring the Promise.all call to after the "initialization" of the tasks and using the `flat` array method we can make performance for recursive directory reading even better, as seen in the attached picture:
image

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks! By any chance can you make a small repo for me to well test this change? I want to make sure the change is not due to fs caches.

**Comment by GalacticHypernova** [comment]
Sure thing! Give me a moment please.

**Comment by GalacticHypernova** [comment]
@pi0
https://github.com/GalacticHypernova/readDirRecursive-Test
It's already preconfigured with the directory to test, which is also the one I used to get the results in the screenshot

**Comment by pi0** [comment]
Okay intresting. Try to change `PR` and `current` order like this:

```js
async function main(){
console.time("PR")
const b =await readdirRecursiveNew("./images")
console.timeEnd("PR")

console.time("current")
const a=await readdirRecursive("./images")
console.timeEnd("current")
}
```

I get the opposite output when swapped away. Seems first run (whichever) fills the OS cache and makes next faster. (basically this refactor is not adding to the parallelism.)

(tested on Macbook Air M2 Node v20.11.0)
```
npx jiti index.ts
PR: 0.731ms
current: 0.34ms
```

**Comment by GalacticHypernova** [comment]
Oh, interesting, allow me to see

**Pull request closed without merging**
