### PR TITLE
feat: add `vercel-blob` driver

### PR DESCRIPTION
**Pull request by PikiLee**
resolves https://github.com/unjs/unstorage/issues/264

### CODE REVIEW

**Comment by ryanweston** [comment]
Is there anything I can do to help get this merged? @pi0

**Comment by MickL** [comment]
@pi0 Can this be merged or is anything missing? Vercel is VERY popular and they have their own file storage [Vercel Blob](https://vercel.com/docs/storage/vercel-blob)

**Comment by pi0** [comment]
Vercel blob uses upstash redis and [upstash driver](https://unstorage.unjs.io/drivers/upstash)  is available on [nightly channel](https://github.com/unjs/unstorage#nightly-release-channel) (via #500) and soon the next release, which gives same functionality.

While Vercel blob is still in Beta, there is a chance that it will be merged to [upstash](https://vercel.com/marketplace/upstash) directly.

<small>(PR, please read [this](https://github.com/pi0/tired-maintainer) before asking for "merge" 🙏🏼)</small>

**Comment by pi0** [comment]
Thanks for PR. I've pushed a few refactors and improvements.

While tests pass against prod, what really concerns me is that we have to make every piece of data publicly accessible, and implementation also requires that we disable random suffixes.

I've added a warning to docs and runtime also but still users might mistakenly leak private info as only and only this driver on server-side has this behavior today. (netlify Blob for example in contrast, AFAIK encrypts and makes them always private).

I will contact vercel team as followup but in the meantime, anyone can directly use `@vercel/blob` in their projects and there is KV storage as well powered by upstash.

**Comment by pi0** [comment]
Update: Private access will eventually be supported. 

For now updated driver to require `access: "public"` config explicitly to make sure devs know the fact.

**Review by pi0 — APPROVED** [review]

**Pull request merged**
