### PR TITLE
feat(drivers): add support for Deno Kv

### LINKED ISSUE #224: Support deno kv
### Describe the feature

Deno has a built-in kv storage, it would be great if we can use it with unstorage!

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by so1ve**
close #224

I'm not sure about how to test it ...

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for the PR 🚀 

Do you mind to merge types and util to the same driver util? (to make project files less sparse)

For testing, we might make a mock interface that is similar to Deno KV. (alternative would be to setup deno and use a HTTP driver but seems overwork for)

**Comment by so1ve** [comment]
> Do you mind to merge types and util to the same driver util?

Done!

> For testing...

How about using deno's native testing?

**Comment by so1ve** [comment]
...WTF where are my changes

**Comment by so1ve** [comment]
??????!!!!!!!! pull deleted my changes??????

**Comment by so1ve** [comment]
I think in need to create a new branch instead of main :( bad habits

**Pull request closed without merging**
