### PR TITLE
draft: feat(drivers): cloudflare durable objects

### LINKED ISSUE #293: [Driver] Cloudflare Durable Objects
### Describe the feature

I would like to build more dynamic applications with writing and retrieving data that work in the environment on which the deploys are created.

Durable Objects from Cloudflare seems like a good solution for this.

- https://developers.cloudflare.com/durable-objects

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by oritwoen**
### 🔗 Linked issue

closes #293 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This is a sketch of the new driver.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jadbox** [comment]
Any updates on this?

**Comment by oritwoen** [comment]
@jadbox I'm testing it locally. I will most likely do updates to the pull request for the code this week.

**Comment by pi0** [comment]
Hi, dear @oritwoen thanks for your interest in helping on this.

I am thinking we could make a more minimal driver that directly accepts `stub` or `getStub()` option to implement rest in unstorage.

Currently, it is tricky to think how because we need higher-order integration. For now, let's keep track via #293 (I am making an overhaul triage on PRs)

**Comment by oritwoen** [comment]
Hi @pi0 I understand. You're right. I managed to run it, but it was very complicated compared to the rest of the drivers and I didn't know how to handle it.

Compared to R2, KV, D1, AI - durable object has a completely different level of abstraction and complexity. I noticed this especially when looking at the code of `@nuxthub/core` and the latest documentation from Cloudflare.

I was actually waiting for it to be simplified on Cloudflare's side, but it's unknown how long it will take and closing the Pull Request makes a lot of sense as long as it looks like this.

Thanks for being vigilant and keeping things tidy ;D

**Comment by pi0** [comment]
I think next step would be `cloudflare-durable` preset in Nitro.

**Pull request closed without merging**
