### PR TITLE
refactor(redis): use named import for `Redis`

### PR DESCRIPTION
**Pull request by tobiasdiez**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

[Since a few versions](https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/CHANGELOG.md?plain=1#L35-L42), ioredis supports named imports. This should improve esm compatibility, and maybe at some point enable treeshaking.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for this PR, but do you think it is an essential change? If ioredis keep supporting default export, it can be safer for projects might have an older version of it.

**Comment by tobiasdiez** [comment]
It's not very essential. I have some troubles with the ioredis import (https://github.com/redis/ioredis/issues/1822, mostly when using vitest) and was hoping this is fixed with this change here. But if you think backwards compatibility is an issue, we can still wait with merging this.

**Comment by pi0** [comment]
Can you help on preparing a reproduction for vitest issue?

What else we can do, is to use `import * from` to dedefault in runtime to have both backward and forward (vitest, ESM) compatibility.

**Comment by tobiasdiez** [comment]
It's sadly hard to reproduce, only occurring in certain situations (which seem to involve importing ioredis another time in code that is tested after using unstorage). Will append a reproduction to the issue as soon as I have one.

You are the expert of cjs/esm imports, so I'll let you decide what's the best import here. I got confused by how ioredis is doing its exports
https://unpkg.com/browse/ioredis@5.3.2/built/index.js

**Comment by pi0** [comment]
Thanks again for PR. Since the named export is added somewhere between 5.x, we might make regressions for some older users. I have added a TODO (404c2f1e3e3fea1e517dfbbdcaa2204f3a5c9b28) to make the change for v2.

**Pull request closed without merging**
