### PR TITLE
feat(http): allow changing responseType

### PR DESCRIPTION
**Pull request by manniL**
### 🔗 Linked issue

#435 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR allows customizing the response type, ensuring that binary files can be sent as blob

Happy for initial feedback, will add tests + docs ☺️ 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks but there is an open discussion and I'm not sure introducing a driver-specific option for return type would be best idea for future compatibility.

**Comment by manniL** [comment]
@pi0 How else would you solve *fetching* blobs using the http driver (from the http server) then?

**Comment by pi0** [comment]
Please use the issue first to showcase your usage, and then we can come up with a solution that is future-proof.

**Comment by manniL** [comment]
@pi0 Of course! Following up in https://github.com/unjs/unstorage/issues/435

**Pull request closed without merging**
